### PR TITLE
udpated logic for the log in and log out

### PR DESCRIPTION
**Pull request by flieckster**
created favicon

### CODE REVIEW

**Review by chorvick — CHANGES_REQUESTED** [review]
leave .gitignore , so env variables don't show

**Review by flieckster — COMMENTED** [review]
removed, .gitignore remove package-lock and env file

**Comment by chorvick** [comment]
lets leave package lock json file intact we don't want to delete from repository or cannot deploy on heroku

**Comment by flieckster** [comment]
just closing this one, added for another

**Pull request closed without merging**
